config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  resources :blogs
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence:  true,
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  
  has_secure_password
  validates :password, presence: true

  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      flash[:notice] = "ログインが必要です。"
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user, {only: [:new, :create, :edit, :confirm, :update, :show, :destroy]}
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, {only: [:edit, :destroy]}

  def new
    if logged_in?
      redirect_to blogs_path
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path
    else
      flash[:danger] = "ログインに失敗しました。"
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    if logged_in?
      redirect_to blogs_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id]) 
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?    
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= form_with(model: blog, local: true) do |form| %>
        <% if blog.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

            <ul>
            <% blog.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group col-sm-8 col-sm-offset-2">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group col-sm-8 col-sm-offset-2">
          <%= form.label :content %>
          <%= form.text_area :content, rows: "8", class: "form-control" %>
        </div>

        <div class="form-group col-sm-8 col-sm-offset-2">
          <%= form.submit "登録する", class: "btn btn-info btn-block" %>
        </div>
        <div class="form-group col-sm-8 col-sm-offset-2">
          <%= link_to 'Back', blogs_path, class: "btn btn-default btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<h2>Editing Blog</h2>
<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Blog', new_blog_path, class: "btn btn-info", style: "color:#fff;" %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.user.name %></td>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog, class: "btn btn-info", style: "color:#fff;" %></td>
        <% if blog.user.id == current_user.id  %>
          <td><%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-success", style: "color:#fff;" %></td>
          <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "color:#fff;" %></td>
      </tr>
        <% end %>   
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<h2>New Blog</h2>
<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/_nav.html.erb
<% if logged_in? %>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to 'Blog', blogs_path, style:"color: #fff; text-decoration: none;" %>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '投稿する', new_blog_path %></li>
          <li><%= link_to 'ホームに戻る', blogs_path %></li>      
          <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Day08</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <% if flash[:notice]%>      
      <div>
        <%= flash[:notice] %>
      </div>      
    <% elsif flash[:danger] %>      
      <div>
        <%= flash[:danger] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>

<%= form_with(model: @user, local:true) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>・<%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div>
    <%= f.label :アカウント名 %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :メールアドレス %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :パスワード %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :パスワード（確認用） %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "新規登録" %>    
  </div>
    <div>
    <%= link_to "ログインする", new_session_path %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス：<%= @user.email %></p>